version: '3'

# WIP, might not be usable.
services:
  yuanjian-app:
    extends:
      file: docker-compose.yml
      service: yuanjian-app-dev
    build:
      args:
        - env=prod
    environment:
      NODE_ENV: production