# yuantuapp.com
server { 
    include                 /etc/nginx/ssl_params.conf;
    server_name             yuantuapp.com;
    ssl_certificate         /certs/yuantuapp.com/fullchain.pem;
    ssl_certificate_key     /certs/yuantuapp.com/privkey.pem;

    location / {
        proxy_pass "http://app:3000/";
        include /etc/nginx/proxy_params.conf;
    }

    error_page   500 502 503 504  /50x.html;
}

# demo.yuantuapp.com
server {
    include                 /etc/nginx/ssl_params.conf;
    server_name             demo.yuantuapp.com;
    ssl_certificate         /certs/demo.yuantuapp.com/fullchain.pem;
    ssl_certificate_key     /certs/demo.yuantuapp.com/privkey.pem;

    location / {
        proxy_pass "http://app-demo:3000/";
        include /etc/nginx/proxy_params.conf;
    }

    error_page   500 502 503 504  /50x.html;
}

# Redirect mentors.org.cn to yuantuapp.com
server { 
    include                 /etc/nginx/ssl_params.conf;
    server_name             mentors.org.cn;
    ssl_certificate         /certs/mentors.org.cn/fullchain.pem;
    ssl_certificate_key     /certs/mentors.org.cn/privkey.pem;

    location / {
        return              301 https://yuantuapp.com$request_uri;
    }
}

# Redirect http to https & support Let's Encrypt challenge
server {
    listen                  80;
    listen                  [::]:80;
    server_name             localhost;

    # https://letsencrypt.org/docs/challenge-types/#http-01-challenge
    # Also see docker-compose.yml.
    location /.well-known/acme-challenge/ {
        root                /var/www/certbot;
    }

    location / {
        return              301 https://$host$request_uri;
    }
}
