# x.yuantuapp.com
server {
    include                 /etc/nginx/ssl_params.conf;
    server_name             x.yuantuapp.com;
    ssl_certificate         /certs/x.yuantuapp.com/fullchain.pem;
    ssl_certificate_key     /certs/x.yuantuapp.com/privkey.pem;

    location / {
        proxy_pass "http://app-x:3000/";
        include /etc/nginx/proxy_params.conf;
    }

    error_page   500 502 503 504  /50x.html;
}

# Redirect http to https & support Let's Encrypt challenge
server {
    listen                  80;
    listen                  [::]:80;
    server_name             localhost;

    # https://letsencrypt.org/docs/challenge-types/#http-01-challenge
    # Also see docker-compose.host1.yml.
    location /.well-known/acme-challenge/ {
        root                /var/www/certbot;
    }

    location / {
        return              301 https://$host$request_uri;
    }
}
