# demo.yuantuapp.com
server {
    include                 /etc/nginx/ssl_params.conf;
    server_name             demo.yuantuapp.com;
    ssl_certificate         /etc/letsencrypt/live/demo.yuantuapp.com/fullchain.pem;
    ssl_certificate_key     /etc/letsencrypt/live/demo.yuantuapp.com/privkey.pem;

    location / {
        proxy_pass "http://demo:3000/";
        include /etc/nginx/proxy_params.conf;
    }

    error_page   500 502 503 504  /50x.html;
}

# ustc.yuantuapp.com
server {
    include                 /etc/nginx/ssl_params.conf;
    server_name             ustc.yuantuapp.com;
    ssl_certificate         /etc/letsencrypt/live/ustc.yuantuapp.com/fullchain.pem;
    ssl_certificate_key     /etc/letsencrypt/live/ustc.yuantuapp.com/privkey.pem;

    location / {
        proxy_pass "http://ustc:3000/";
        include /etc/nginx/proxy_params.conf;
    }

    error_page   500 502 503 504  /50x.html;
}

# xhef.yuantuapp.com
server {
    include                 /etc/nginx/ssl_params.conf;
    server_name             xhef.yuantuapp.com;
    ssl_certificate         /etc/letsencrypt/live/xhef.yuantuapp.com/fullchain.pem;
    ssl_certificate_key     /etc/letsencrypt/live/xhef.yuantuapp.com/privkey.pem;

    location / {
        proxy_pass "http://xhef:3000/";
        include /etc/nginx/proxy_params.conf;
    }

    error_page   500 502 503 504  /50x.html;
}

# Redirect www.yuantuapp.com to yuantuapp.com
server {
    include                 /etc/nginx/ssl_params.conf;
    server_name             www.yuantuapp.com;
    ssl_certificate         /etc/letsencrypt/live/www.yuantuapp.com/fullchain.pem;
    ssl_certificate_key     /etc/letsencrypt/live/www.yuantuapp.com/privkey.pem;

    location / {
        return              301 https://yuantuapp.com$request_uri;
    }
}

# Redirect mentors.org.cn to yuantuapp.com
server { 
    include                 /etc/nginx/ssl_params.conf;
    server_name             mentors.org.cn;
    ssl_certificate         /etc/letsencrypt/live/mentors.org.cn/fullchain.pem;
    ssl_certificate_key     /etc/letsencrypt/live/mentors.org.cn/privkey.pem;

    location / {
        return              301 https://yuantuapp.com$request_uri;
    }
}

# Redirect book.yuantuapp.com to notion site
server {
    include                 /etc/nginx/ssl_params.conf;
    server_name             book.yuantuapp.com;
    ssl_certificate         /etc/letsencrypt/live/book.yuantuapp.com/fullchain.pem;
    ssl_certificate_key     /etc/letsencrypt/live/book.yuantuapp.com/privkey.pem;

    location / {
        return              301 https://yuanjian.notion.site/10936363e9078051a5bef7f8ccc6d306;
    }
}

# Redirect doc.yuantuapp.com to notion site
server {
    include                 /etc/nginx/ssl_params.conf;
    server_name             doc.yuantuapp.com;
    ssl_certificate         /etc/letsencrypt/live/doc.yuantuapp.com/fullchain.pem;
    ssl_certificate_key     /etc/letsencrypt/live/doc.yuantuapp.com/privkey.pem;

    location / {
        return              301 https://yuanjian.notion.site/10936363e9078051a5bef7f8ccc6d306;
    }
}

# Redirect http to https & support Let's Encrypt challenge
server {
    listen                  80;
    listen                  [::]:80;
    server_name             localhost;

    # https://letsencrypt.org/docs/challenge-types/#http-01-challenge
    # Also see docker-compose.yml.
    location /.well-known/acme-challenge/ {
        root                /var/www/certbot;
    }

    location / {
        return              301 https://$host$request_uri;
    }
}
