#!/usr/bin/env bash

# Usage: ./tools/importPearlStudents.sh <path_to_csv>
#
# This script imports PearlStudent data from a CSV file into the database using psql.
# Existing data will be overwritten on primary key (pearlId) conflict.
#
# The expected CSV format is (with header):
#
# 姓名,珍珠号,身份证后四位
# 张三,12345678901,1234
# 李四,98765432109,5678
#
# Ensure that the environment variable DATABASE_URI is properly set before running.

if [ -z "$1" ]; then
  echo "Usage: $0 <path_to_csv>"
  exit 1
fi

CSV_FILE="$1"

if [ ! -f "$CSV_FILE" ]; then
  echo "Error: File not found: $CSV_FILE"
  exit 1
fi

if [ -z "$DATABASE_URI" ]; then
  echo "Error: DATABASE_URI environment variable is not set."
  exit 1
fi

# Read the CSV file line by line
# We skip the first line (header) using tail
imported_count=0

# Create a temporary file to hold the SQL commands
SQL_FILE=$(mktemp)

echo "Importing records from $CSV_FILE to $SQL_FILE ..."

echo "BEGIN;" > "$SQL_FILE"

while IFS=',' read -r name pearlId nationalIdLastFour; do
  # Remove trailing carriage returns (\r) which might be present in Windows CSVs
  ### COMMENTED OUT TO OPTIMIZE FOR TIME
  # name=$(echo "$name" | tr -d '\r' | xargs)
  # pearlId=$(echo "$pearlId" | tr -d '\r' | xargs)
  nationalIdLastFour=$(echo "$nationalIdLastFour" | tr -d '\r' | xargs)

  # Skip empty lines
  if [ -z "$pearlId" ] || [ -z "$name" ]; then
    continue
  fi

  # Ensure nationalIdLastFour is lowercased if it contains letters (usually X)
  nationalIdLastFour=$(echo "$nationalIdLastFour" | tr '[:upper:]' '[:lower:]')

  # Escape single quotes in name to prevent SQL injection
  ### COMMENTED OUT TO OPTIMIZE FOR TIME
  # name=$(echo "$name" | sed "s/'/''/g")

  # Generate the upsert SQL command
  # The table name generated by Sequelize is 'PearlStudents' (plural form of model name unless specified)
  cat >> "$SQL_FILE" <<EOF
INSERT INTO "PearlStudents" ("pearlId", "name", "lowerCaseNationalIdLastFour", "createdAt", "updatedAt")
VALUES ('$pearlId', '$name', '$nationalIdLastFour', NOW(), NOW())
ON CONFLICT ("pearlId") DO UPDATE
SET "name" = EXCLUDED."name",
    "lowerCaseNationalIdLastFour" = EXCLUDED."lowerCaseNationalIdLastFour",
    "updatedAt" = NOW();
EOF

  imported_count=$((imported_count + 1))

  if [ $((imported_count % 1000)) -eq 0 ]; then
    echo "Imported $imported_count records"
  fi

done < <(tail -n +2 "$CSV_FILE")

echo "COMMIT;" >> "$SQL_FILE"

echo "Importing records from $SQL_FILE to databsae ..."

# Execute the SQL file using psql
psql "$DATABASE_URI" -f "$SQL_FILE" -v ON_ERROR_STOP=1 > /dev/null

if [ $? -eq 0 ]; then
  echo "Successfully imported/updated $imported_count PearlStudent records."
else
  echo "Error during database import."
  rm "$SQL_FILE"
  exit 1
fi

rm "$SQL_FILE"
exit 0
