import { expect } from "chai";
import { Transaction } from "sequelize";
import db from "../database/db";
import sequelize from "../database/sequelize";
import {
  listImpl,
  updateImpl,
  saveSummaryImpl,
  AI_MINUTES_SUMMARY_KEY,
} from "./summaries";
import User from "../../shared/User";

describe("summaries", () => {
  let transaction: Transaction;

  beforeEach(async () => {
    transaction = await sequelize.transaction();
  });

  afterEach(async () => {
    await transaction.rollback();
  });

  async function createTestUser(roles: any[] = []) {
    const user = await db.User.create(
      {
        email: `test-user-${Date.now()}-${Math.random()}@test.com`,
        name: "Test User",
        roles,
      },
      { transaction },
    );
    return {
      id: user.id,
      name: user.name,
      url: null,
      roles: user.roles,
      email: user.email,
      phone: user.phone,
      wechat: user.wechat,
      menteeStatus: user.menteeStatus,
      pointOfContact: null,
      pointOfContactNote: null,
    } as User;
  }

  async function createTestGroup(isPublic = true) {
    return await db.Group.create(
      {
        name: "Test Group",
        public: isPublic,
      },
      { transaction },
    );
  }

  async function createTestTranscript(groupId: string) {
    const id = `test-transcript-${Date.now()}-${Math.random()}`;
    return await db.Transcript.create(
      {
        id,
        groupId: groupId,
        startedAt: new Date(),
        endedAt: new Date(),
      },
      { transaction },
    );
  }

  async function createTestSummary(transcriptId: string, markdown: string) {
    return await db.Summary.create(
      {
        transcriptId,
        key: AI_MINUTES_SUMMARY_KEY,
        markdown,
        initialLength: markdown.length,
        deletedLength: 0,
      },
      { transaction },
    );
  }

  describe("saveSummaryImpl", () => {
    it("should successfully create a Transcript and create a Summary", async () => {
      const group = await createTestGroup();
      const transcriptId = `test-transcript-save-${Date.now()}`;
      const startedAt = Date.now() - 1000 * 60 * 60; // 1 hour ago
      const endedAt = Date.now();
      const key = AI_MINUTES_SUMMARY_KEY;
      const markdown = "# Test Summary\nThis is a test summary generated by saveSummaryImpl.";

      await saveSummaryImpl(
        transcriptId,
        group.id,
        startedAt,
        endedAt,
        key,
        markdown,
        transaction,
      );

      const transcript = await db.Transcript.findByPk(transcriptId, { transaction });
      expect(transcript).to.exist;
      expect(transcript?.groupId).to.equal(group.id);
      expect(transcript?.startedAt?.getTime()).to.equal(startedAt);
      expect(transcript?.endedAt?.getTime()).to.equal(endedAt);

      const summary = await db.Summary.findOne({
        where: { transcriptId, key },
        transaction,
      });
      expect(summary).to.exist;
      expect(summary?.markdown).to.equal(markdown);
      expect(summary?.initialLength).to.equal(markdown.length);
      expect(summary?.deletedLength).to.equal(0);
    });

    it("should successfully update an existing Transcript and create a Summary", async () => {
      const group = await createTestGroup();
      // Pre-create the transcript to test the "update" branch of upsert
      const existingTranscript = await createTestTranscript(group.id);

      const startedAt = Date.now() - 1000 * 60 * 60; // 1 hour ago
      const endedAt = Date.now();
      const key = AI_MINUTES_SUMMARY_KEY;
      const markdown = "# Updated Test Summary\nThis is a test summary generated by saveSummaryImpl for an existing transcript.";

      await saveSummaryImpl(
        existingTranscript.id,
        group.id,
        startedAt,
        endedAt,
        key,
        markdown,
        transaction,
      );

      const transcript = await db.Transcript.findByPk(existingTranscript.id, { transaction });
      expect(transcript).to.exist;
      // StartedAt and EndedAt should be updated to the new values
      expect(transcript?.startedAt?.getTime()).to.equal(startedAt);
      expect(transcript?.endedAt?.getTime()).to.equal(endedAt);

      const summary = await db.Summary.findOne({
        where: { transcriptId: existingTranscript.id, key },
        transaction,
      });
      expect(summary).to.exist;
      expect(summary?.markdown).to.equal(markdown);
      expect(summary?.initialLength).to.equal(markdown.length);
      expect(summary?.deletedLength).to.equal(0);
    });
  });

  describe("listImpl", () => {
    it("should return the AI minutes summary for a transcript", async () => {
      const me = await createTestUser(["MentorshipManager"]);
      const group = await createTestGroup();
      await db.GroupUser.create(
        { userId: me.id, groupId: group.id },
        { transaction },
      );
      const transcript = await createTestTranscript(group.id);
      const summaryMarkdown = "This is a test summary";
      await createTestSummary(transcript.id, summaryMarkdown);

      const result = await listImpl(me, transcript.id, transaction);

      expect(result).to.have.lengthOf(1);
      expect(result[0].transcriptId).to.equal(transcript.id);
      expect(result[0].key).to.equal(AI_MINUTES_SUMMARY_KEY);
      expect(result[0].markdown).to.equal(summaryMarkdown);
    });

    it("should throw error if user has no permission to access group history", async () => {
      const me = await createTestUser(["Volunteer"]);
      const group = await createTestGroup(false);
      // User is not in the group
      const transcript = await createTestTranscript(group.id);

      try {
        await listImpl(me, transcript.id, transaction);
        expect.fail("Expected error to be thrown");
      } catch (error: any) {
        expect(error.message).to.contain("没有权限访问分组");
      }
    });
  });

  describe("updateImpl", () => {
    it("should throw error if user has no permission to update summary", async () => {
      const me = await createTestUser(["Volunteer"]); // Not a manager, not in
      // group
      const group = await createTestGroup(false);
      const transcript = await createTestTranscript(group.id);
      const originalMarkdown = "Original summary text";
      await createTestSummary(transcript.id, originalMarkdown);

      const newMarkdown = "Updated summary text";

      try {
        await updateImpl(
          me,
          transcript.id,
          AI_MINUTES_SUMMARY_KEY,
          newMarkdown,
          transaction,
        );
        expect.fail("Expected error to be thrown");
      } catch (error: any) {
        expect(error.message).to.contain("没有权限访问分组");
      }
    });

    it("should allow updating a summary if user has permission", async () => {
      const me = await createTestUser(["GroupManager"]);
      const group = await createTestGroup(false);
      const transcript = await createTestTranscript(group.id);
      const originalMarkdown = "Original summary text";
      await createTestSummary(transcript.id, originalMarkdown);

      const newMarkdown = "Original summary text.";

      await updateImpl(
        me,
        transcript.id,
        AI_MINUTES_SUMMARY_KEY,
        newMarkdown,
        transaction,
      );

      const updatedSummary = await db.Summary.findOne({
        where: {
          transcriptId: transcript.id,
          key: AI_MINUTES_SUMMARY_KEY,
        },
        transaction,
      });
      expect(updatedSummary?.markdown).to.equal(newMarkdown);
    });
  });
});
