import * as tencentMeetingModule from "../TencentMeeting";
import * as summariesModule from "./summaries";
import axios from "axios";
import sinon from "sinon";
import { saveSummaryIfNotExistImpl } from "./saveSummary";
import * as saveSummaryModule from "./saveSummary";

import { expect } from "chai";
import crypto from "crypto";
import { Transaction } from "sequelize";
import db from "../database/db";
import sequelize from "../database/sequelize";
import { listImpl, updateImpl, AI_MINUTES_SUMMARY_KEY } from "./summaries";

import User from "../../shared/User";

describe("summaries", () => {
  let transaction: Transaction;

  beforeEach(async () => {
    transaction = await sequelize.transaction();
  });

  afterEach(async () => {
    await transaction.rollback();
  });

  async function createTestUser(roles: any[] = []) {
    const user = await db.User.create(
      {
        email: `test-user-${Date.now()}-${crypto.randomUUID()}@test.com`,
        name: "Test User",
        roles,
      },
      { transaction },
    );
    return {
      id: user.id,
      name: user.name,
      url: null,
      roles: user.roles,
      email: user.email,
      phone: user.phone,
      wechat: user.wechat,
      menteeStatus: user.menteeStatus,
      pointOfContact: null,
      pointOfContactNote: null,
    } as User;
  }

  async function createTestGroup(isPublic = true) {
    return await db.Group.create(
      {
        name: "Test Group",
        public: isPublic,
      },
      { transaction },
    );
  }

  async function createTestTranscript(groupId: string) {
    const id = `test-transcript-${Date.now()}-${crypto.randomUUID()}`;
    return await db.Transcript.create(
      {
        id,
        groupId: groupId,
        startedAt: new Date(),
        endedAt: new Date(),
      },
      { transaction },
    );
  }

  async function createTestSummary(transcriptId: string, markdown: string) {
    return await db.Summary.create(
      {
        transcriptId,
        key: AI_MINUTES_SUMMARY_KEY,
        markdown,
        initialLength: markdown.length,
        deletedLength: 0,
      },
      { transaction },
    );
  }

  describe("saveSummaryImpl", () => {
    it("should successfully create a Transcript and create a Summary", async () => {
      const group = await createTestGroup();
      const transcriptId = `test-transcript-save-${Date.now()}`;
      const startedAt = Date.now() - 1000 * 60 * 60; // 1 hour ago
      const endedAt = Date.now();
      const key = AI_MINUTES_SUMMARY_KEY;
      const markdown =
        "# Test Summary\nThis is a test summary generated by saveSummaryImpl.";

      await saveSummaryIfNotExistImpl(
        transcriptId,
        group.id,
        startedAt,
        endedAt,
        key,
        markdown,
        transaction,
      );

      const transcript = await db.Transcript.findByPk(transcriptId, {
        transaction,
      });
      expect(transcript !== null).to.equal(true);
      expect(transcript?.groupId).to.equal(group.id);
      expect(transcript?.startedAt?.getTime()).to.equal(startedAt);
      expect(transcript?.endedAt?.getTime()).to.equal(endedAt);

      const summary = await db.Summary.findOne({
        where: { transcriptId, key },
        transaction,
      });
      expect(summary !== null).to.equal(true);
      expect(summary?.markdown).to.equal(markdown);
      expect(summary?.initialLength).to.equal(markdown.length);
      expect(summary?.deletedLength).to.equal(0);
    });

    it("should successfully update an existing Transcript and create a Summary", async () => {
      const group = await createTestGroup();
      // Pre-create the transcript to test the "update" branch of upsert
      const existingTranscript = await createTestTranscript(group.id);

      const startedAt = Date.now() - 1000 * 60 * 60; // 1 hour ago
      const endedAt = Date.now();
      const key = AI_MINUTES_SUMMARY_KEY;
      const markdown =
        "# Updated Test Summary\nThis is a test summary generated by saveSummaryImpl for an existing transcript.";

      await saveSummaryIfNotExistImpl(
        existingTranscript.id,
        group.id,
        startedAt,
        endedAt,
        key,
        markdown,
        transaction,
      );

      const transcript = await db.Transcript.findByPk(existingTranscript.id, {
        transaction,
      });
      expect(transcript !== null).to.equal(true);
      // StartedAt and EndedAt should be updated to the new values
      expect(transcript?.startedAt?.getTime()).to.equal(startedAt);
      expect(transcript?.endedAt?.getTime()).to.equal(endedAt);

      const summary = await db.Summary.findOne({
        where: { transcriptId: existingTranscript.id, key },
        transaction,
      });
      expect(summary !== null).to.equal(true);
      expect(summary?.markdown).to.equal(markdown);
      expect(summary?.initialLength).to.equal(markdown.length);
      expect(summary?.deletedLength).to.equal(0);
    });
  });

  describe("listImpl", () => {
    it("should return the AI minutes summary for a transcript", async () => {
      const me = await createTestUser(["MentorshipManager"]);
      const group = await createTestGroup();
      await db.GroupUser.create(
        { userId: me.id, groupId: group.id },
        { transaction },
      );
      const transcript = await createTestTranscript(group.id);
      const summaryMarkdown = "This is a test summary";
      await createTestSummary(transcript.id, summaryMarkdown);

      const result = await listImpl(me, transcript.id, transaction);

      expect(result).to.have.lengthOf(1);
      expect(result[0].transcriptId).to.equal(transcript.id);
      expect(result[0].key).to.equal(AI_MINUTES_SUMMARY_KEY);
      expect(result[0].markdown).to.equal(summaryMarkdown);
    });

    it("should throw error if user has no permission to access group history", async () => {
      const me = await createTestUser(["Volunteer"]);
      const group = await createTestGroup(false);
      // User is not in the group
      const transcript = await createTestTranscript(group.id);

      try {
        await listImpl(me, transcript.id, transaction);
        expect.fail("Expected error to be thrown");
      } catch (error: any) {
        expect(error.message).to.contain("没有权限访问分组");
      }
    });
  });

  describe("updateImpl", () => {
    it("should throw error if user has no permission to update summary", async () => {
      const me = await createTestUser(["Volunteer"]); // Not a manager, not in
      // group
      const group = await createTestGroup(false);
      const transcript = await createTestTranscript(group.id);
      const originalMarkdown = "Original summary text";
      await createTestSummary(transcript.id, originalMarkdown);

      const newMarkdown = "Updated summary text";

      try {
        await updateImpl(
          me,
          transcript.id,
          AI_MINUTES_SUMMARY_KEY,
          newMarkdown,
          transaction,
        );
        expect.fail("Expected error to be thrown");
      } catch (error: any) {
        expect(error.message).to.contain("没有权限访问分组");
      }
    });

    it("should allow updating a summary if user has permission", async () => {
      const me = await createTestUser(["GroupManager"]);
      const group = await createTestGroup(false);
      const transcript = await createTestTranscript(group.id);
      const originalMarkdown = "Original summary text";
      await createTestSummary(transcript.id, originalMarkdown);

      const newMarkdown = "Original summary text.";

      await updateImpl(
        me,
        transcript.id,
        AI_MINUTES_SUMMARY_KEY,
        newMarkdown,
        transaction,
      );

      const updatedSummary = await db.Summary.findOne({
        where: {
          transcriptId: transcript.id,
          key: AI_MINUTES_SUMMARY_KEY,
        },
        transaction,
      });
      expect(updatedSummary?.markdown).to.equal(newMarkdown);
    });
  });
});

describe("downloadSummaries functions", () => {
  let transaction: Transaction;

  beforeEach(async () => {
    transaction = await sequelize.transaction();
  });

  afterEach(async () => {
    sinon.restore();
    await transaction.rollback();
  });

  it("findMissingSummariesforTmUser should filter ready records and map to descriptors", async () => {
    const listRecordsStub = sinon.stub(tencentMeetingModule, "listRecords");
    listRecordsStub.resolves([
      {
        meeting_id: "m1",
        meeting_record_id: "mr1",
        state: 3,
        record_files: [
          {
            record_file_id: "f1",
            record_start_time: Date.now() - 1000 * 60,
            record_end_time: Date.now(),
          },
        ],
      } as any, // ready
      {
        meeting_id: "m2",
        meeting_record_id: "mr2",
        state: 2,
        record_files: [],
      } as any, // not ready
    ]);

    const group = await db.Group.create(
      { name: "Test Group", public: true },
      { transaction },
    );

    sinon
      .stub(db.MeetingHistory, "findOne")
      .resolves({ groupId: group.id } as any);
    sinon.stub(tencentMeetingModule, "getSpeakerStats").resolves([]);
    sinon.stub(tencentMeetingModule, "getKey2FileAddresses").resolves({
      ai_minutes: [
        { file_type: "txt", download_address: "http://example.com/txt" },
      ],
    } as any);

    sinon
      .stub(axios, "get")
      .resolves({ data: "会议摘要\n\nSome important points." });
    sinon
      .stub(saveSummaryModule, "saveSummaryIfNotExist")
      .callsFake((desc: any) => {
        descs.push(desc);
      });
    sinon.stub(saveSummaryModule, "hasSummary").resolves(false as any);

    const descs: any[] = [];
    await summariesModule.findMissingSummariesforTmUser("tm-user", descs);

    void expect(listRecordsStub.calledWith("tm-user")).to.be.true;
    expect(descs.length).to.be.greaterThan(0);
    expect(descs[0].transcriptId).to.equal("f1");
    expect(descs[0].groupId).to.equal(group.id);
  });

  it("processRecord should generate summary descriptors correctly", async () => {
    const meetingId = "m-process-1";
    const group = await db.Group.create(
      { name: "Test Group 2", public: true },
      { transaction },
    );
    const groupId = group.id;
    const tmUserId = "tm-user-1";
    const transcriptId = "file-1";

    const record = {
      meeting_id: meetingId,
      meeting_record_id: "mr-1",
      state: 3,
      record_files: [
        {
          record_file_id: transcriptId,
          record_start_time: Date.now() - 1000 * 60 * 60, // 1 hour ago
          record_end_time: Date.now(),
        },
      ],
    };

    sinon
      .stub(tencentMeetingModule, "getSpeakerStats")
      .resolves([{ speakerName: "Speaker 1", totalTime: 10 }] as any);

    sinon.stub(tencentMeetingModule, "getKey2FileAddresses").resolves({
      ai_minutes: [
        { file_type: "txt", download_address: "http://example.com/txt" },
      ],
    } as any);

    sinon
      .stub(axios, "get")
      .resolves({ data: "会议摘要\n\nSome important points." });

    const descs: any[] = [];

    const findOneStub = sinon
      .stub(db.MeetingHistory, "findOne")
      .resolves({ groupId } as any);

    sinon
      .stub(saveSummaryModule, "saveSummaryIfNotExist")
      .callsFake((desc: any) => {
        descs.push(desc);
      });
    sinon.stub(saveSummaryModule, "hasSummary").resolves(false as any);

    await summariesModule.processRecord(record as any, tmUserId, descs);

    void expect(findOneStub.called).to.be.true;

    expect(descs.length).to.be.greaterThan(0);
    expect(descs[0].transcriptId).to.equal(transcriptId);
    expect(descs[0].groupId).to.equal(groupId);
  });

  it("downloadUrl should return data", async () => {
    const axiosGetStub = sinon
      .stub(axios, "get")
      .resolves({ data: "summary content" });
    const content = await summariesModule.downloadUrl("http://example.com");
    void expect(axiosGetStub.calledWith("http://example.com")).to.be.true;
    expect(content).to.equal("summary content");
  });

  it("formatAiMinutesSummary should return null if summary is empty", () => {
    void expect(summariesModule.formatAiMinutesSummary("", [])).to.be.null;
  });

  it("formatAiMinutesSummary should format correctly", () => {
    const summary = "会议摘要\n\nSome important points.";
    const res = summariesModule.formatAiMinutesSummary(summary, [
      { speakerName: "Speaker 1", totalTime: 10 } as any,
    ]);
    void expect(res).to.not.be.null;
    expect(res).to.include("Some important points.");
    expect(res).to.include("Speaker 1");
  });
});
