name: Daily Backup

permissions:
  contents: read

on:
  schedule:
    # Runs at 1 AM Beijing Time (UTC+8) every day.
    - cron: "0 17 * * *"
  workflow_dispatch:

jobs:
  backup:
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJSON(vars.DEPLOYMENT_MATRIX || '{"include":[{"host_id":"host0","hostname_var":"HOSTNAME0","env_files":".env .env.ustc .env.xhef .env.demo"},{"host_id":"host1","hostname_var":"HOSTNAME1","env_files":".env.x"}]}') }}

    steps:
    - name: Install SSH client
      run: sudo apt-get install -y openssh-client

    - name: Add SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}
        known_hosts: ${{ vars[matrix.hostname_var] }}
        config: |
          Host ${{ vars[matrix.hostname_var] }}
            User ${{ secrets.SERVER_SSH_USERNAME }}
            StrictHostKeyChecking no

    - name: Execute Backup on Server
      run: |
        ssh ${{ secrets.SERVER_SSH_USERNAME }}@${{ vars[matrix.hostname_var] }} << 'EOF'
          set -e
          cd ~/app

          mkdir -p backups
          rm -rf backups/*

          for env_file in ${{ matrix.env_files }}; do
            [ -e "$env_file" ] || continue

            # Extract DATABASE_URI and DATABASE_BACKUP_KEY
            DATABASE_URI=$(sudo grep '^DATABASE_URI=' "$env_file" | sed -e 's/^DATABASE_URI=//' | sed -e "s/^'//;s/'$//" | sed -e 's/^"//;s/"$//')
            DATABASE_BACKUP_KEY=$(sudo grep '^DATABASE_BACKUP_KEY=' "$env_file" | sed -e 's/^DATABASE_BACKUP_KEY=//' | sed -e "s/^'//;s/'$//" | sed -e 's/^"//;s/"$//')

            if [ -n "$DATABASE_URI" ] && [ -n "$DATABASE_BACKUP_KEY" ]; then
              echo "Backing up database for $env_file"
              pg_dump "$DATABASE_URI" -F p -b -v -f backup.sql && gzip -f backup.sql
              openssl enc -aes-256-cbc -salt -pbkdf2 -pass "pass:$DATABASE_BACKUP_KEY" -in backup.sql.gz -out backups/backup_${env_file}.sql.gz.enc
              rm -f backup.sql backup.sql.gz
            else
              echo "Skipping $env_file: DATABASE_URI or DATABASE_BACKUP_KEY not found."
            fi
          done

          tar -cvf all_backups.tar -C backups .
          rm -rf backups
        EOF

    - name: Download Backup Archive
      run: |
        scp ${{ secrets.SERVER_SSH_USERNAME }}@${{ vars[matrix.hostname_var] }}:~/app/all_backups.tar ./all_backups.tar

    - name: Clean up remote backup archive
      run: |
        ssh ${{ secrets.SERVER_SSH_USERNAME }}@${{ vars[matrix.hostname_var] }} "rm -f ~/app/all_backups.tar"

    - name: Upload Backup to Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: database-backups-${{ matrix.host_id }}
        path: all_backups.tar
        retention-days: 30
