name: Daily Reset Demo Data

permissions: {}

on:
  schedule:
    # Runs at 00:00 Beijing Time (UTC+8) every day.
    - cron: "0 16 * * *"
  workflow_dispatch:

jobs:
  run_scheduled_task:
    runs-on: ubuntu-latest

    steps:
      - name: Reset demo data
        env:
          INTEGRATION_MATRIX: ${{ secrets.INTEGRATION_MATRIX }}
        run: |
          CLEAN_MATRIX=$(printf '%s\n' "$INTEGRATION_MATRIX" | perl -0777 -pe 's/,\s*\}/}/g')
          AUTH_TOKEN=$(echo "$CLEAN_MATRIX" | jq -r '."demo.yuantuapp.com"')
          curl --fail-with-body -X POST -H "Authorization: Bearer ${AUTH_TOKEN}" https://demo.yuantuapp.com/api/v1/cron.resetDemoData
