name: Hourly Cron Jobs

permissions: {}

on:
  schedule:
    # Runs at the 8th minute of every hour. Do not run close to 30m boundaries
    # because there may be cases where users wait for a bit longer than
    # `gracePeriodMinutes` to join a meeting after they have clicked the join
    # button, and meetings are often scheduled at 30m boundaries.
    #
    # Note that Github have large scheduling delays which are often more than
    # a few minutes.
    #
    - cron: "8 * * * *"

jobs:
  run_scheduled_task:
    runs-on: ubuntu-latest

    steps:
      - name: Sync meetings
        run: |
          curl -X POST -H "Authorization: Bearer ${{ secrets.INTEGRATION_AUTH_TOKEN }}" https://${{ vars.SERVER_HOSTNAME }}/api/v1/cron.syncMeetings
      
      - name: Create auto tasks
        run: |
          curl -X POST -H "Authorization: Bearer ${{ secrets.INTEGRATION_AUTH_TOKEN }}" https://${{ vars.SERVER_HOSTNAME }}/api/v1/cron.createAutoTasks
      
      - name: Send scheduled emails
        run: |
          curl -X POST -H "Authorization: Bearer ${{ secrets.INTEGRATION_AUTH_TOKEN }}" https://${{ vars.SERVER_HOSTNAME }}/api/v1/cron.sendScheduledEmails
