name: Hourly Send Tasks And Emails

permissions: {}

on:
  schedule:
    - cron: "10 * * * *"
  workflow_dispatch:

jobs:
  run_scheduled_task:
    uses: ./.github/workflows/run-cron.yml
    with:
      cron_tasks: "cron.createAutoTasks cron.sendScheduledNotifications"
    secrets:
      SERVER_SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}
      SERVER_SSH_USERNAME: ${{ secrets.SERVER_SSH_USERNAME }}
