name: Hourly Sync XHEF Meetings

permissions: {}

on:
  schedule:
    # Stagger starts with +6 mins from Yuantu sync meeting to avoid API call
    # over quota issue with Tencent Meeting. See hourly-sync-yuantu-meetings.yml
    # for other important comments.
    #
    - cron: "14 * * * *"
  workflow_dispatch:

jobs:
  run_scheduled_task:
    runs-on: ubuntu-latest

    steps:
      - name: Sync meetings
        run: |
          curl -f -X POST -H "Authorization: Bearer ${{ secrets.XHEF_INTEGRATION_AUTH_TOKEN }}" https://${{ vars.XHEF_SERVER_HOSTNAME }}/api/v1/cron.syncMeetings
