name: Weekly Cron Jobs

permissions: {}

on:
  schedule:
    # Runs at 2:42 AM China Standard Time every Friday.
    - cron: "42 18 * * 4"
  workflow_dispatch:

jobs:
  run_scheduled_task:
    uses: ./.github/workflows/run-curl.yml
    with:
      cron_tasks: "cron.auditLastMentorshipMeetings cron.recycleMeetings cron.purgeOldData"
    secrets:
      INTEGRATION_AUTH_TOKENS_JSON: ${{ secrets.INTEGRATION_AUTH_TOKENS_JSON }}
